config/routes.rb
Rails.application.routes.draw do
  get "/path/to/your/consumer/page", to: "cards#consumer", as: "consumer"
  get "/path/to/your/accept/page", to: "cards#accept", as: "accept"
  root 'cards#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
    has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
   def show
   end
   
   def index
   end
   
   def post
   end
   
   def consumer
   end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/accept.html.erb
<div class="col-sm-12">
    <center>
        
        <div class="nav-bar">
        <div id="title1">
            AMERICAN EXPRESS
        </div>
        </div>
        <div id="amex-phrase"><img id="amex-logo" src="https://www.seeklogo.net/wp-content/uploads/2018/04/american-express-logo.png" /> DON'T <span id="apply-logo">Live Life</span> WITHOUT IT</div>
        <br>
    </center>
</div>
<div class="col-md-12" id="toprow">
    <div id="step-four-left" class="col-md-3">
        <center>
            <img id="amex-plat2" src="https://icm.aexp-static.com/content/dam/one-amex/benefits/en_us/images/large/ShopSaks.jpg" />
        </center>
    </div>
    <div class="col-md-2">
        <span id="thumbs" class="glyphicon glyphicon-thumbs-up"></span>
    </div>
    <div class="col-md-4">
    
        <img id="amex-plat2" src="https://icm.aexp-static.com/content/dam/one-amex/benefits/en_us/images/large/AirportLoungeAccessProgramOpen.jpg" />
    </div>

</div>
<div class="col-sm-12" id="steptwobackground"> 
    <center>
        
        <br>
        <h1>Congratulations!! You've been approved for The Platinum Card!</h1>
        <br>
    </center>
</div>

<div class="col-sm-12"> 
    <div id="step-two-left" class="col-md-4">
        <center>
    <img id="amex-plat2" src="https://d1a3f4spazzrp4.cloudfront.net/chameleon/cms/uploads/2017/3/29/1490831867-amex__hero.jpg" />
    <img id="amex-plat2" src="https://d1a3f4spazzrp4.cloudfront.net/chameleon/cms/uploads/2017/3/30/1490847066-uber__amex2x.jpg" />
    
    </center>
    </div>
    
    
    
    <div id="step-two-right" class="col-md-4">
    <ul>
        <h3>$200 UBER CREDIT</h3>
Arrive in comfort for less. Enjoy $15 in Uber credits for U.S. rides each month plus a bonus $20 in December1, for a total of up to $200 in annual Uber savings.‡

1 Credit and Uber VIP status available to Basic Card Member only.
    </ul>
    <ul>
        <h3> 5X POINTS ON FLIGHTS & HOTELS</h3>
See more of the world by earning 5X Membership Rewards® points on flights booked directly with airlines or on AmexTravel.com, and eligible hotels booked on AmexTravel.com.‡

Plus, earn 1X points on all other purchases whether you’re paying bills or shopping.
        
    </ul>
    <ul>
        
        <h3>$200 AIRLINE FEE CREDIT</h3>
Take off with up to $200 each year in statement credits towards incidentals like in-flight meals, checked bags and more with your selected qualifying airline.
    </ul>
    </div>
    
</div>

app/views/cards/consumer.html.erb
<div class="col-sm-12">
    <center>
        
        <div class="nav-bar">
        <div id="title1">
            AMERICAN EXPRESS
        </div>
        </div>
        <div id="amex-phrase"><img id="amex-logo" src="https://www.seeklogo.net/wp-content/uploads/2018/04/american-express-logo.png" /> DON'T <span id="apply-logo">apply</span> WITHOUT IT</div>
        <br>
    </center>
</div>

<div class="col-md-12" id="toprow">
    
    <div id="step-four-left" class="col-md-3">
        <center>
            <img id="amex-plat2" src="https://icm.aexp-static.com/content/dam/one-amex/benefits/en_us/images/large/AirportLoungeAccessProgramOpen.jpg" />
        </center>
    </div>
    <div class="col-md-2">
        <span class="glyphicon glyphicon-road"></span>
    </div>
    <div class="col-md-2">
    
        <img id="amex-blue" src="https://icm.aexp-static.com/content/dam/one-amex/benefits/en_us/images/medium/200AirlineFeeCredit.jpg" />
    </div>
    
</div>
<br>
<div class="col-sm-12" id="steptwobackground"> 
    <div id="step-two-left" class="col-md-6" >
        <br>
        <br>
        <br>
    Thank you for your interest in the Platinum Card.
    <br>
    At this time, we need a bit more info from you before we can make a decision. 
    <br>
    Please follow the steps on the right side.</div>
    <div id="step-two-right" class="col-md-6">
    <span class="step-two-label">Additional Steps Needed:</span>
    
    <div class="add-id">
        <ul class="id-list">
            <div>
                <span>Upload a Student ID</span><br>
            <form>
            <div class="form-group">
                <input type="file" class="form-control-file" onchange="updateStudentId();">
            </div>
        </form>            
        </ul>
        <img class="student-id" class="add-id-img" src="https://i.imgur.com/XfNR3zg.png" />
        </div>
        
        <div class="add-id" id="second-div">
        <ul class="id-list">
            <div>
            Upload an Employee ID <br>
        <form>
            <div class="form-group">
                <input type="file" class="form-control-file" onchange="updateGoogleId();">
            </div>
        </form>            
        </ul>
        <img class="google-id" class="add-id-img" src="https://i.imgur.com/EXyUGAp.png" />
        </div>
        </div>
    </div>    
    

</div>
<div class="col-sm-12"> 
<br>
<br>
<center>
<div class="btn btn-primary">
    <%= link_to accept_path, id: "an-id", :class => "btn" do %>
    Submit to Start Your Platinum Journey
    <% end %>
</center>
</div>
</div>

app/views/cards/index.html.erb
<script type="text/javascript">
$("#exampleFormControlFile1").change(function(ev) {
    console.log("hello worldsssss");
});
</script>

    <div class="col-sm-12">
    <center>
        
        <div class="nav-bar">
        <div id="title1">
            AMERICAN EXPRESS
        </div>
        </div>
        <div id="amex-phrase"><img id="amex-logo" src="https://www.seeklogo.net/wp-content/uploads/2018/04/american-express-logo.png" /> DON'T <span id="apply-logo">apply</span> WITHOUT IT</div>
        <br>
    </center>
    </div>

<div class="col-sm-12" id="personalrow">
    <div class="col-sm-3">
        <br>
        <span class="personal-info">PERSONAL INFORMATION</span>
        <br> 
        <span class="secure">Secure.</span> <span class="learn-more">Learn More.</span>
    </div>
   
    
    <div class="col-sm-3">
    
    </div>
</div>


  <div id="get-decision" class="col-md-6">
    <div class="step-two-info get-decs">Get a decision in as</div>
    <div class="step-two-info get-decs">little as 30 seconds.</div>
    <img id="amex-plat" src="https://creditcard.americanexpress.com/assets/default/card-art/plat_480x304.png" />
  </div>


<div class="col-md-12" id="toprow">
<div class="col-sm-12" id="userphoto">
    <center>
        <p class="get-started">Let's Get Started!</p>
        
        <div class="upload-left">
          <p class="step-one-label">Step One</p>
          <label class="upload-license-label" for="exampleFormControlFile1">Upload your Driver's License</label>
        </div>
        
        <div class="upload-right">
        <span class="glyphicon glyphicon-user"></span>
        <br>
        <span><img class="driver-license" src="https://i.imgur.com/fVVEymD.jpg" /></span>
        <form>
            <div class="form-group">
                <input type="file" class="form-control-file" id="exampleFormControlFile1" onchange="updateImage();">
            </div>
        </form>
        </div>
    </center>
    </div>
</div>
</div>



<br>
<br>
<br>
<div class="col-sm-12" id="steptwobackground"> 
<br>
<div id="step-two-left" class="col-md-6" >
    <form>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputFirstname">First Name</label>
          <input type="text" class="form-control" id="inputFirstname2" placeholder="">
        </div>
        <div class="form-group col-md-6">
          <label for="inputLastname">Last Name</label>
          <input type="text" class="form-control" id="inputLastname2" placeholder="">
        </div>
      </div>
      <div class="form-group col-md-6">
        <label for="inputAddress">Address</label>
        <input type="text" class="form-control" id="inputAddress2" placeholder="">
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputCity">City</label>
          <input type="text" class="form-control" id="inputCity2">
        </div>
        <div class="form-group col-md-4">
          <label for="inputState">State</label>
          <input type="text" class="form-control" id="inputState2">
        </div>
        <div class="form-group col-md-2">
          <label for="inputZip">Zip</label>
          <input type="text" class="form-control" id="inputZip2">
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-4">
        </div>
        <div class="form-group col-md-4">
        <label for="inputEmail">Email Address</label>
        <input type="text" class="form-control" id="inputEmailaddress2">
        </div>
         <div class="form-group col-md-4">
         </div>
        </div>
        
    
    </form>
</div>
<div id="step-two-right" class="col-md-6">
    <br>

    <center>
    
    <span class="step-two-label">Step Two</span>
    <br>
    <span class="step-two-info">Verify Your Information</span>
    <br>
    <br>
      <span id="check12" class="glyphicon glyphicon-ok-circle"></span>
    </center>
</div>
</div>


<div class="col-sm-12" id="termsrow"> 
<br>
<br>

    <div id="step-two-left" class="col-md-6">
    
        <div>
            <span class="step-two-info">
            Step Three
            </span>
        <br>
        <span class="glyphicon glyphicon-list-alt"></span><span class="step-two-info">&nbspConfirm</span>
        </div>
    </div>

    <div id="step-two-right" class="col-md-6">
    <div class="form-row">
            <div class="form-group col-md-4">
            </div>
            <div class="form-group col-md-8">
                By submitting this application, I certify that I have read, met, and agreed to all of the terms, conditiions, and disclosures outlined which contain rate, fee, and other important information.
                <br>
                <br>
                <div class="btn btn-primary">
                    <%= link_to consumer_path, id: "an-id", :class => "btn" do %>
                    Agree &amp; Submit
                    <% end %>
                </div>
            </div>
            <div class="form-group col-md-2">
            </div>
    </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amexhack007</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>